version: 1.2
workflows:
  - subclass: CWL
    primaryDescriptorPath: /sc_atac_seq_prep_process_analyze.cwl
    testParameterFiles:
      - /sc_atac_seq_prep_process_analyze.json
    name: HuBMAP_scATAC-seq_Pipeline
