dist: bionic

services:
   - docker

language: python

python:
  - "3.6"

install:
  - pip install -r requirements_host.txt

script:
 #Execute each line separately using the literal style block scalar for yaml
 # http://yaml.org/spec/1.2/spec.html#id2795688
  - |
     #.test.sh     
     cwltool --version
     pwd
     ls -al
     df -h
     sudo du -hsx ./* | sort -n | head -100
     cd $TRAVIS_BUILD_DIR/tests/
     pwd
     ls -al
     # Have Travis CI wait for a set time even if the workflows do not provide
     # output (stdout or stderr)
     # E.g argument of 30 means if no output is recieved from the worklfow 
     # for 30 minutes travis will fail the workflow (default is 10 minutes)
     travis_wait 30 ./run_sc_atac_seq_tests.sh
